packages:
  # root directory
  - '.'
  # all packages in subdirs of packages/
  - 'packages/**'
  - 'playground/**'
  # exclude packages that are inside test/ directories
  - '!**/test/**' # '!' means exclude
